### PR TITLE
Docs - Reorganize with diataxis

### PR DESCRIPTION
**Pull request by lucas-tortora**
# Description of change

- Reorganized docs to follow diataxis
  - Added missing meta tags
  - Fixed broken links
  - Updated readmes
  - Deleted unused files
  - Updated wiki build process
   
## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation Enhancement

## How the change has been tested

wiki was built locally

## Change checklist

- [x] I have followed the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by lucas-tortora** [comment]
@Dr-Electron , @arnauorriols , @aleksei-korolev, could you review this when you get a chance? Thanks!

**Comment by Dr-Electron** [comment]
Can we merge the new build system PR first? 😅

**Review by Dr-Electron — CHANGES_REQUESTED** [review]
Structure looks good to me. But will approve once we merged the new build system

**Review by Dr-Electron — APPROVED** [review]

**Comment by lucas-tortora** [comment]
@arnauorriols, whenever you're ready, the conflicts have been sorted  :)

**Comment by lucas-tortora** [comment]
@arnauorriols , could you take a look and possibly merge this whenever you have a moment?

**Review by kwek20 — APPROVED** [review]

**Review by DyrellC — APPROVED** [review]
Let's get this one merged so we can deal with the other changes as well

**Pull request merged**
